[project]
name = "ml-adventures"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "graphviz>=0.21",
    "ipykernel>=6.30.0",
    "numpy>=2.3.2",
    "pip>=25.2",
]
